import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import '@/config/di/reflect-metadata'
import QueryClientProvider from '@/app/providers/QueryClient.provider'
import { Toaster } from '@/components/ui/toaster'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${raleway.className} antialiased`}
      >
        <QueryClientProvider>
          {children}
          <Toaster />
        </QueryClientProvider>
      </body>
    </html>
  )
}
