import Sidebar from '@/app/dashboard/user-management/components/SidebarSubmodule.component'
import '@/config/di/reflect-metadata'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function SidebarLayout ({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <div className="flex">
        <Sidebar />
        <main className="flex-1 ml-44 container mx-auto p-4 space-y-6">
        {children}
        </main>
    </div>

  )
}
